### ISSUE TITLE
wrong hash value after update to 10.2.1.4

### ISSUE THREAD

**Issue by Tschoepler** [owncloud/updater#517]
hi,

after updating to owncloud 10.2.1.4 i get the notification 

```Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)```

and when i list the invalid files the following shows up.

```
Results
=======
- core
	- INVALID_HASH
		- updater/CHANGELOG.md

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [updater/CHANGELOG.md] => Array
                        (
                            [expected] => 30634ecf94beb635907baa4c1f9a144080890f172db28ce09515b5f9e5415255bbfab51dfdcecdf5eb3a7eaf97b558463758a5222d5eca696b2f8eb50ba28451
                            [current] => 2255145e06bdf90e19f890cb28060a6950ab6bc9b27e249b66a6ba235b8402ae65864c029016611f6a3399d3e4921c24f1ffe6ad24c88ad4ce1b3b9918266cfc
                        )

                )

        )

)
```

i tried downloading the CHANGELOG.md to my server from the master branch, but this gave me an invalid/non-matching hash value respond. any idea which file version i need to download to get rid of this error message?

thanks

**Comment by davitol** [comment]
cc @VicDeo JFYI

**Comment by VicDeo** [comment]
all channels except daily are unified to provide 10.2.1 at the moment so initial OC version is more important here

**Comment by muellermartin** [comment]
For me this issue also appeared after the automatic update to 10.2.1.4 and is related to the files missing that are mentioned in these forum threads:

- https://central.owncloud.org/t/solved-missing-files-when-migrating-from-from-10-0-10-4-to-10-2-1-4/20959
- https://central.owncloud.org/t/code-signing-issue-recent-upgrade-to-10-2-1-4/20923/2

I could manually download all the files, except the mentioned CHANGELOG.md file, as the checksum does not match and only one version is available. Is there a fix available or planned?

**Comment by muellermartin** [comment]
The error is gone for me. Unfortunately I can't remember how I solved it, but maybe I also used the file from the release package as the checksum matches.

**Comment by VicDeo** [comment]
Should be fixed in the next updater release

**Comment by DaveDreezer** [comment]
Just got the notice to update to 10.3.0. Same error, same files that failed in the 10.2.1.4.  Not fixed in the next updater release.

**Comment by VicDeo** [comment]
@DaveDreezer >Not fixed in the next updater release. 

It depends on the definition of **the next updater release.**  :book: 
For me the next **updater** release hasn't been done yet and the core is shipped with Updater 1.0.0
https://github.com/owncloud/updater/releases/tag/v1.0.0

**Comment by DaveDreezer** [comment]
fair enough. thank you.

**Comment by jmac05r1** [comment]
Having same issue on README.md file .. any fix?

**Comment by rjaeckel** [comment]
@jmac05r1
> Having same issue on README.md file .. any fix?

Just fixed that on my installation. As long as the expected hash of the mentioned CHANGELOG.md is exactly `30634ecf94beb635907baa4c1f9a144080890f172db28ce09515b5f9e5415255bbfab51dfdcecdf5eb3a7eaf97b558463758a5222d5eca696b2f8eb50ba28451` the above mentioned zip contains the correct file:

> @Tschoepler @muellermartin does changelog from https://github.com/owncloud/updater/archive/v1.0.0.zip match?

**Comment by jmac05r1** [comment]
Hello, 

Thank you, I was able to get this working by downloading the owncloud tarball and moving just that readme.md file to overwrite the existing one

**Comment by VicDeo** [comment]
Fixed in updater 1.0.1 https://github.com/owncloud/updater/releases/tag/v1.0.1
To be released with  OC 10.4

**Comment by alariej** [comment]
I just updated to 10.15.0.2 on a arm64 Ubuntu 22.04 RPI, and I get the warning "There were problems with the code integrity check. More information..." on the web client. Pressing the re-check button just spins forever. Running "occ integrity:check-core" in the terminal lists a bunch of files (updater/CHANGELOG.md, etc.) under "INVALID_HASH". Any way to quickly re-install only the updater? 🤯

**Comment by iasdeoupxe** [comment]
@alariej Usually not the best idea to post a new issue in a 3-4 year old and already solved issue.

Just create a new one as otherwise this won't get noticed by the app maintainers.

**Comment by jnweiger** [comment]
@alariej maybe this workaround also helps in your case? https://github.com/owncloud/updater/issues/749#issuecomment-2299032078

**Comment by alariej** [comment]
Hi @jnweiger, workaround did work, exactly what I was looking for. Many thanks!
